// Fetches Minecraft patch notes from Mojang's official launcher feed
// (the same JSON the in-game launcher consumes) and writes them as MDX into
// content/<locale>/news (releases) and content/<locale>/sneakpeeks
// (snapshots/previews).
//
// Mojang publishes patch notes in English only, so for DE we run the
// content through LibreTranslate. Results are cached on disk (sha1 of
// source text) — re-runs only translate genuinely new content.
//
// Run:
//   npm run fetch:news              # both locales
//   node scripts/fetch-news.mjs --locale=en
//   node scripts/fetch-news.mjs --locale=de
//
// Network failures never fail the build — the script exits 0.

import { writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import path from 'node:path';
import TurndownService from 'turndown';
import { translate, looksUntranslated, flushTranslationCache } from './lib/translate.mjs';

// Body translation cap. Mojang patch notes can be 50-80kb of HTML.
// Below this we translate (in chunks); above, we keep the English body
// and show a notice. Trade-off: bigger = more coverage but slow first run.
const BODY_TRANSLATE_LIMIT = Number(process.env.BODY_TRANSLATE_LIMIT) || 20_000;

const DE_PARTIAL_NOTICE = [
  '> **Hinweis:** Diese Patch Notes wurden teilweise automatisch übersetzt.',
  '> Der englische Originaltext wird unten gezeigt, weil er für die automatische Übersetzung zu lang ist.',
  '',
  '',
].join('\n');

const LAUNCHER_BASE = 'https://launchercontent.mojang.com';
const FEED_BASE = `${LAUNCHER_BASE}/v2`;
const PATCH_NOTES_URL = `${FEED_BASE}/javaPatchNotes.json`;
const BEDROCK_URL = `${FEED_BASE}/bedrockPatchNotes.json`;

const CONTENT_ROOT = path.join(process.cwd(), 'content');
const MAX_PER_FEED = Number(process.env.MAX_PER_FEED) || 30;
const AUTO_PREFIX = 'auto-';

const LOCALES_ALL = ['en', 'de'];
const argLocale = process.argv
  .find((a) => a.startsWith('--locale='))
  ?.split('=')[1];
const TARGET_LOCALES = argLocale ? [argLocale] : LOCALES_ALL;

function resolveLauncherUrl(rel) {
  if (!rel) return undefined;
  if (rel.startsWith('http')) return rel;
  const trimmed = rel.replace(/^\/+/, '');
  if (trimmed.startsWith('v2/')) return `${LAUNCHER_BASE}/${trimmed}`;
  return `${FEED_BASE}/${trimmed}`;
}

const turndown = new TurndownService({
  headingStyle: 'atx',
  codeBlockStyle: 'fenced',
  bulletListMarker: '-',
  emDelimiter: '_',
});
turndown.remove(['style', 'script']);
turndown.addRule('keepImages', {
  filter: 'img',
  replacement: (_c, node) => {
    const src = node.getAttribute('src') || '';
    const alt = node.getAttribute('alt') || '';
    const abs = resolveLauncherUrl(src);
    if (!abs) return '';
    return `![${alt}](${abs})`;
  },
});

function slugify(s) {
  return String(s)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^\w\s.-]/g, '')
    .replace(/[\s_.]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function yamlString(s) {
  return `"${String(s ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, ' ')
    .trim()}"`;
}

function categoryFor(type) {
  const t = String(type || '').toLowerCase();
  if (t === 'release') return 'news';
  return 'sneakpeeks';
}

async function fetchJson(url) {
  const res = await fetch(url, {
    headers: { 'user-agent': 'minewiki-fetcher/1.0 (+local build)' },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.json();
}

async function removeAutoGenerated(locale) {
  for (const cat of ['news', 'sneakpeeks']) {
    const dir = path.join(CONTENT_ROOT, locale, cat);
    let files = [];
    try {
      files = await readdir(dir);
    } catch {
      continue;
    }
    await Promise.all(
      files
        .filter((f) => f.startsWith(AUTO_PREFIX) && f.endsWith('.mdx'))
        .map((f) => unlink(path.join(dir, f))),
    );
  }
}

function buildFrontmatter({ title, date, category, excerpt, cover, tags, source }) {
  const lines = [
    '---',
    `title: ${yamlString(title)}`,
    `date: ${yamlString(date)}`,
    `category: ${yamlString(category)}`,
    `excerpt: ${yamlString(excerpt)}`,
  ];
  if (cover) lines.push(`cover: ${yamlString(cover)}`);
  if (tags?.length) {
    lines.push(`tags: [${tags.map((t) => yamlString(t)).join(', ')}]`);
  }
  lines.push(`_generated: true`);
  if (source) lines.push(`_source: ${yamlString(source)}`);
  lines.push('---', '');
  return lines.join('\n');
}

/**
 * Resolves the final per-locale title/excerpt/body. For DE we translate via
 * LibreTranslate (cached). Title + excerpt are always translated (tiny &
 * cheap); body is only translated when it fits the LibreTranslate budget,
 * otherwise we keep the English body and prepend a notice.
 *
 * All translation calls are serialized globally by lib/translate.mjs so we
 * never overwhelm the public instance.
 */
async function localiseArticle({ locale, title, excerpt, html }) {
  if (locale === 'en') return { title, excerpt, html, partial: false };

  // Sequential — the translation module also serialises internally, but
  // sequential at call-site means we get reasonable progress logging.
  const tTitle =
    (await translate(title, { source: 'en', target: locale, format: 'text' })) || title;
  const tExcerpt =
    (await translate(excerpt, { source: 'en', target: locale, format: 'text' })) || excerpt;

  let tHtml = html;
  let partial = false;
  if (html.length <= BODY_TRANSLATE_LIMIT) {
    const candidate = await translate(html, {
      source: 'en',
      target: locale,
      format: 'html',
    });
    if (candidate && !looksUntranslated(html, candidate)) {
      tHtml = candidate;
    } else {
      partial = true;
    }
  } else {
    partial = true;
  }

  return { title: tTitle, excerpt: tExcerpt, html: tHtml, partial };
}

async function writeArticleForLocale({ entry, html, category, sourceUrl, locale }) {
  const dir = path.join(CONTENT_ROOT, locale, category);
  await mkdir(dir, { recursive: true });

  const slugSrc = entry.version || entry.title || entry.id;
  const slug = slugify(slugSrc);
  if (!slug) return false;

  const rawTitle = entry.title || `Minecraft ${entry.version}`;
  const rawExcerpt =
    entry.shortText ||
    entry.text ||
    turndown.turndown(html).replace(/[#>*_`\[\]\(\)]/g, ' ').replace(/\s+/g, ' ').slice(0, 180).trim();

  const localised = await localiseArticle({
    locale,
    title: rawTitle,
    excerpt: rawExcerpt,
    html,
  });

  let md = turndown.turndown(localised.html).trim();
  if (locale === 'de' && localised.partial) md = DE_PARTIAL_NOTICE + md;
  const date = entry.date || new Date().toISOString().slice(0, 10);

  const coverPath = entry.image?.url || entry.imageURL || entry.playPageImage?.url;
  const cover = resolveLauncherUrl(coverPath);

  const tags = ['update'];
  if (entry.type) tags.push(String(entry.type));
  if (entry.version) tags.push(String(entry.version));

  const fm = buildFrontmatter({
    title: localised.title,
    date,
    category,
    excerpt: localised.excerpt,
    cover,
    tags,
    source: sourceUrl,
  });

  const filename = `${AUTO_PREFIX}${slug}.mdx`;
  await writeFile(path.join(dir, filename), fm + md + '\n', 'utf8');
  return true;
}

async function processPatchNotes(label, indexUrl) {
  console.log(`→ ${label}: ${indexUrl}`);
  let index;
  try {
    index = await fetchJson(indexUrl);
  } catch (e) {
    console.warn(`  ! Skipping ${label}: ${e.message}`);
    return 0;
  }

  const entries = (index.entries || []).slice(0, MAX_PER_FEED);
  let written = 0;
  let i = 0;

  for (const entry of entries) {
    i++;
    let html = entry.body;
    let articleUrl = indexUrl;

    if (!html && entry.contentPath) {
      articleUrl = resolveLauncherUrl(entry.contentPath);
      try {
        const full = await fetchJson(articleUrl);
        html = full.body || full.text || '';
      } catch (e) {
        console.warn(`  ! ${entry.title || entry.id}: ${e.message}`);
        continue;
      }
    }
    if (!html) html = entry.shortText || '';
    if (!html) continue;

    const category = categoryFor(entry.type);

    process.stdout.write(`  [${i}/${entries.length}] ${entry.title || entry.id}\r`);

    for (const locale of TARGET_LOCALES) {
      try {
        const ok = await writeArticleForLocale({
          entry,
          html,
          category,
          sourceUrl: articleUrl,
          locale,
        });
        if (ok && locale === TARGET_LOCALES[0]) written++;
      } catch (e) {
        console.warn(`\n  ! Write failed [${locale}] ${entry.title}: ${e.message}`);
      }
    }
  }
  process.stdout.write(' '.repeat(80) + '\r');
  console.log(`  ✓ ${label}: wrote ${written} entries × ${TARGET_LOCALES.length} locales`);
  return written;
}

async function main() {
  console.log(
    `Fetching Minecraft news from Mojang launcher feeds (locales: ${TARGET_LOCALES.join(', ')})…`,
  );
  if (TARGET_LOCALES.includes('de')) {
    console.log('DE: translating via LibreTranslate (cached). First run will be slow.\n');
  } else {
    console.log('');
  }

  try {
    for (const locale of TARGET_LOCALES) {
      await removeAutoGenerated(locale);
    }
    const totals = await Promise.all([
      processPatchNotes('Java patch notes', PATCH_NOTES_URL),
      processPatchNotes('Bedrock patch notes', BEDROCK_URL),
    ]);
    const total = totals.reduce((a, b) => a + b, 0);
    console.log(`\nDone. Total source articles processed: ${total}`);
  } catch (e) {
    console.error(`\n! Fetch failed: ${e.message}`);
    console.error('  Existing content preserved; continuing.');
  } finally {
    await flushTranslationCache();
  }
}

main();
