// Fetches Minecraft patch notes from Mojang's official launcher feed
// (the same JSON the in-game launcher consumes) and writes them as MDX
// into content/news (releases) and content/sneakpeeks (snapshots/previews).
//
// Run manually:   npm run fetch:news
// Auto on build:  via the `prebuild` hook in package.json
//
// Network failures never fail the build — the script exits 0 and leaves
// existing content in place so deploys remain reproducible.

import { writeFile, mkdir, readdir, unlink, readFile } from 'node:fs/promises';
import path from 'node:path';
import TurndownService from 'turndown';

const LAUNCHER_BASE = 'https://launchercontent.mojang.com';
const FEED_BASE = `${LAUNCHER_BASE}/v2`; // contentPath values are relative to /v2/
const PATCH_NOTES_URL = `${FEED_BASE}/javaPatchNotes.json`;
const BEDROCK_URL = `${FEED_BASE}/bedrockPatchNotes.json`;

function resolveLauncherUrl(rel) {
  if (!rel) return undefined;
  if (rel.startsWith('http')) return rel;
  // contentPath is "javaPatchNotes/<hash>.json" or "/v2/images/foo.jpg" — normalise both.
  const trimmed = rel.replace(/^\/+/, '');
  if (trimmed.startsWith('v2/')) return `${LAUNCHER_BASE}/${trimmed}`;
  return `${FEED_BASE}/${trimmed}`;
}

const CONTENT_ROOT = path.join(process.cwd(), 'content');

// Cap how far back we go — patch notes go back to 2011, you don't want all of it.
const MAX_PER_FEED = 30;

// Files we write are prefixed so we can clean them on each run without
// touching hand-authored articles.
const AUTO_PREFIX = 'auto-';

const turndown = new TurndownService({
  headingStyle: 'atx',
  codeBlockStyle: 'fenced',
  bulletListMarker: '-',
  emDelimiter: '_',
});

// Strip Mojang's tracking pixels and inline styles that Turndown otherwise
// passes through as raw HTML noise.
turndown.remove(['style', 'script']);
turndown.addRule('keepImages', {
  filter: 'img',
  replacement: (_content, node) => {
    const src = node.getAttribute('src') || '';
    const alt = node.getAttribute('alt') || '';
    const abs = resolveLauncherUrl(src);
    if (!abs) return '';
    return `![${alt}](${abs})`;
  },
});

function slugify(s) {
  return String(s)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^\w\s.-]/g, '')
    .replace(/[\s_.]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function yamlString(s) {
  // Double-quoted YAML scalar — escape backslashes and double quotes.
  return `"${String(s ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, ' ')
    .trim()}"`;
}

function categoryFor(type) {
  const t = String(type || '').toLowerCase();
  if (t === 'release') return 'news';
  // 'snapshot' | 'pre_release' | 'release_candidate' | etc.
  return 'sneakpeeks';
}

async function fetchJson(url) {
  const res = await fetch(url, {
    headers: { 'user-agent': 'minewiki-fetcher/1.0 (+local build)' },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.json();
}

async function removeAutoGenerated() {
  for (const cat of ['news', 'sneakpeeks']) {
    const dir = path.join(CONTENT_ROOT, cat);
    let files = [];
    try {
      files = await readdir(dir);
    } catch {
      continue;
    }
    await Promise.all(
      files
        .filter((f) => f.startsWith(AUTO_PREFIX) && f.endsWith('.mdx'))
        .map((f) => unlink(path.join(dir, f))),
    );
  }
}

function buildFrontmatter({ title, date, category, excerpt, cover, tags, source }) {
  const lines = [
    '---',
    `title: ${yamlString(title)}`,
    `date: ${yamlString(date)}`,
    `category: ${yamlString(category)}`,
    `excerpt: ${yamlString(excerpt)}`,
  ];
  if (cover) lines.push(`cover: ${yamlString(cover)}`);
  if (tags?.length) {
    lines.push(`tags: [${tags.map((t) => yamlString(t)).join(', ')}]`);
  }
  lines.push(`_generated: true`);
  if (source) lines.push(`_source: ${yamlString(source)}`);
  lines.push('---', '');
  return lines.join('\n');
}

async function writeArticle({ entry, body, category, sourceUrl }) {
  const dir = path.join(CONTENT_ROOT, category);
  await mkdir(dir, { recursive: true });

  const md = turndown.turndown(body || '').trim();
  const slugSrc = entry.version || entry.title || entry.id;
  const slug = slugify(slugSrc);
  if (!slug) return false;

  const date =
    entry.date ||
    entry.publishedAt ||
    new Date().toISOString().slice(0, 10);

  const excerpt =
    entry.shortText ||
    entry.text ||
    md.replace(/[#>*_`\[\]\(\)]/g, ' ').replace(/\s+/g, ' ').slice(0, 180).trim();

  const coverPath = entry.image?.url || entry.imageURL || entry.playPageImage?.url;
  const cover = resolveLauncherUrl(coverPath);

  const tags = ['update'];
  if (entry.type) tags.push(String(entry.type));
  if (entry.version) tags.push(String(entry.version));

  const fm = buildFrontmatter({
    title: entry.title || `Minecraft ${entry.version}`,
    date,
    category,
    excerpt,
    cover,
    tags,
    source: sourceUrl,
  });

  const filename = `${AUTO_PREFIX}${slug}.mdx`;
  await writeFile(path.join(dir, filename), fm + md + '\n', 'utf8');
  return true;
}

async function processPatchNotes(label, indexUrl) {
  console.log(`→ ${label}: ${indexUrl}`);
  let index;
  try {
    index = await fetchJson(indexUrl);
  } catch (e) {
    console.warn(`  ! Skipping ${label}: ${e.message}`);
    return 0;
  }

  const entries = (index.entries || []).slice(0, MAX_PER_FEED);
  let written = 0;

  for (const entry of entries) {
    let body = entry.body;
    let articleUrl = indexUrl;

    // Many feeds only carry shortText in the index — full body is at contentPath.
    if (!body && entry.contentPath) {
      articleUrl = resolveLauncherUrl(entry.contentPath);
      try {
        const full = await fetchJson(articleUrl);
        body = full.body || full.text || '';
      } catch (e) {
        console.warn(`  ! ${entry.title || entry.id}: ${e.message}`);
        continue;
      }
    }
    if (!body) body = entry.shortText || '';
    if (!body) continue;

    try {
      const ok = await writeArticle({
        entry,
        body,
        category: categoryFor(entry.type),
        sourceUrl: articleUrl,
      });
      if (ok) written++;
    } catch (e) {
      console.warn(`  ! Write failed for ${entry.title}: ${e.message}`);
    }
  }

  console.log(`  ✓ ${label}: wrote ${written} articles`);
  return written;
}

async function main() {
  console.log('Fetching Minecraft news from Mojang launcher feeds…\n');

  try {
    await removeAutoGenerated();

    const totals = await Promise.all([
      processPatchNotes('Java patch notes', PATCH_NOTES_URL),
      processPatchNotes('Bedrock patch notes', BEDROCK_URL),
    ]);

    const total = totals.reduce((a, b) => a + b, 0);
    console.log(`\nDone. Total articles written: ${total}`);
  } catch (e) {
    // Never fail the build because of upstream issues.
    console.error(`\n! Fetch failed: ${e.message}`);
    console.error('  Existing content preserved; continuing.');
    process.exit(0);
  }
}

main();
